// Music and sound effects for the whole game (Web Audio API). Everything the game wants heard goes
// through the cue bus (src/audio/bus.js: sfx('doorOpen')); this module listens and plays it, and plays
// the music of the current scene (setScene: the lobby waltz in the menu, the night ambience in a game,
// the tenser final-round piece in round 8, a stinger on the end screen). The files and the mix:
// src/audio/library.js (generated by tools/audio/build.py) and src/audio/sounds.js.
//
//   const audio = createAudio({ settings });
//   audio.setScene('menu' | 'intro' | 'game' | 'final' | 'end' | 'none');
//   audio.stinger('win');              // (or sfx('win') through the bus)
//   audio.applySettings();             // after the Music / Sound effects setting changes
//   audio.prefetch('final');           // decode a track ahead of its scene
//
// Browsers (iOS Safari above all) allow no sound until the page is touched: the audio context is
// created on the first touch, click or key, which also starts the scene's music. Until then cues are
// dropped. Music files are decoded only while their scene is near (a decoded minute of music is
// ~20 MB); the short effects are all decoded once, after that first touch. When the page is hidden
// the sound pauses. Nothing here ever throws: without Web Audio the game is simply silent.
import { onSfx } from './bus.js';
import { MUSIC, EFFECTS } from './library.js';
import { CUES, SCENES, TRACK_GAIN, STINGER_GAIN, MAX_VOICES } from './sounds.js';

const BASE = new URL('../../assets/audio/', import.meta.url);
const dbGain = d => Math.pow(10, d / 20);
const LIMITER_TRIM = dbGain(-1.71);   // undoes the limiter's own make-up gain (see ensureContext)
const SILENT = { setScene() {}, stinger() {}, stopStinger() {}, applySettings() {}, prefetch() {}, play() {}, scene: 'none', state: () => ({ ok: false }) };

export function createAudio({ settings, doc = document, win = window } = {}) {
  const AC = win.AudioContext || win.webkitAudioContext;
  const log = [];                                   // the last cues asked for (tests: window.__audioLog)
  win.__audioLog = log;
  if (!AC) { onSfx(name => note(name, 'no web audio')); return SILENT; }

  let ctx = null;
  let master = null, musicBus = null, sfxBus = null;
  let unlocked = false;
  let scene = 'none';
  const buffers = new Map();     // file -> AudioBuffer
  const loading = new Map();     // file -> Promise<AudioBuffer|null>
  const failed = new Set();
  const tracks = new Map();      // music track name -> { src, gain, fading, timer }
  let current = null;            // the track the scene wants (playing or loading)
  const voices = [];             // effects sounding now: { name, src, low, out, gain }
  const lastAt = {};
  const lastSlice = {};

  function note(name, why, extra) {
    log.push({ t: Math.round(performance.now()), name, why, ...(extra || {}) });
    if (log.length > 300) log.splice(0, log.length - 300);
  }
  const level = name => {
    const c = settings?.choice?.(name);
    return typeof c?.gain === 'number' ? c.gain : name === 'music' ? 0.5 : 1;
  };
  // Music and Sound effects both Off: the audio is put to sleep and the iPad's audio session given
  // back, so the player's own music (another app) is not paused by a game making no sound.
  const silent = () => level('music') <= 0 && level('sound') <= 0;
  function setSession(type) {
    try { if (win.navigator?.audioSession && win.navigator.audioSession.type !== type) win.navigator.audioSession.type = type; } catch { /* older Safari */ }
  }

  // --- the context, created on the first gesture -------------------------------------------------
  function ensureContext() {
    if (ctx) return ctx;
    try { ctx = new AC({ latencyHint: 'interactive' }); } catch { try { ctx = new AC(); } catch { ctx = null; } }
    if (!ctx) return null;
    master = ctx.createGain();
    musicBus = ctx.createGain();
    sfxBus = ctx.createGain();
    musicBus.gain.value = level('music');
    sfxBus.gain.value = level('sound');
    musicBus.connect(master); sfxBus.connect(master);
    // A safety limiter before the speakers: a loud effect at its random top level, over the music
    // and footsteps, must never clip. Transparent below about -1.3 dBFS (the browser's compressor adds
    // its own make-up gain of ~+1.7 dB at these settings: the master trims it back), a ceiling of
    // about -1.1 dBFS above that.
    let lim = null;
    try {
      lim = ctx.createDynamicsCompressor?.() || null;
      if (lim) {
        lim.threshold.value = -3; lim.knee.value = 0; lim.ratio.value = 20;
        lim.attack.value = 0.002; lim.release.value = 0.12;
      }
    } catch { lim = null; }
    if (lim) { master.gain.value = LIMITER_TRIM; master.connect(lim); lim.connect(ctx.destination); }
    else master.connect(ctx.destination);
    ctx.onstatechange = () => { if (ctx.state === 'running') onRunning(); };
    return ctx;
  }
  function onRunning() {
    if (unlocked) { syncMusic(0.6); return; }
    unlocked = true;
    note('unlocked', 'running', { rate: ctx.sampleRate });
    syncMusic();
    preloadEffects();
  }
  function gesture() {
    // Chrome warns about a context made outside a real gesture (a touch's pointerdown is not one):
    // wait for one that is.
    const ua = win.navigator?.userActivation;
    if (ua && !ua.isActive) return;
    if (silent()) return;                   // both Off: no audio at all (turning one on wakes it)
    try {
      if (!ensureContext()) return;
      // iOS: let the game's sound play like a game's, even with the ring switch on silent (Safari 17+)
      setSession('playback');
      if (ctx.state !== 'running') {
        const p = ctx.resume?.();
        p?.then?.(() => { if (ctx.state === 'running') onRunning(); }).catch?.(() => {});
        // (old iOS: a silent buffer started inside the touch wakes the hardware)
        const b = ctx.createBuffer(1, 1, 22050);
        const s = ctx.createBufferSource();
        s.buffer = b; s.connect(ctx.destination); s.start(0);
      } else if (!unlocked) onRunning();
    } catch (err) { console.warn('sound could not start:', err); }
  }
  for (const ev of ['pointerdown', 'pointerup', 'touchend', 'mousedown', 'click', 'keydown']) {
    win.addEventListener(ev, gesture, { capture: true, passive: true });
  }
  // Hidden page: pause everything (and give the device back its audio); back: carry on.
  doc.addEventListener('visibilitychange', () => {
    if (!ctx) return;
    try {
      if (doc.hidden) ctx.suspend?.().catch?.(() => {});
      else if (unlocked && !silent()) ctx.resume?.().catch?.(() => {});
    } catch { /* ignore */ }
  });

  // --- loading -----------------------------------------------------------------------------------
  function decode(data) {
    return new Promise((resolve, reject) => {
      // (older Safari: callbacks only)
      const p = ctx.decodeAudioData(data, resolve, reject);
      if (p && typeof p.then === 'function') p.then(resolve, reject);
    });
  }
  // The file's bytes: fetched ahead (before the first tap, see setScene) or now.
  const bytes = new Map();       // file -> Promise<ArrayBuffer>
  const fetchBytes = file => fetch(new URL(file, BASE)).then(r => { if (!r.ok) throw new Error(`${r.status} ${file}`); return r.arrayBuffer(); });
  function prefetchBytes(file) {
    if (!bytes.has(file) && !buffers.has(file) && !failed.has(file)) bytes.set(file, fetchBytes(file).catch(() => null));
  }
  function load(file) {
    if (buffers.has(file)) return Promise.resolve(buffers.get(file));
    if (loading.has(file)) return loading.get(file);
    if (!ctx || failed.has(file)) return Promise.resolve(null);
    const early = bytes.get(file);
    bytes.delete(file);
    const p = (early ? early.then(b => b || fetchBytes(file)) : fetchBytes(file))
      .then(decode)
      .then(buf => { buffers.set(file, buf); loading.delete(file); return buf; })
      .catch(err => { failed.add(file); loading.delete(file); console.warn('a sound could not be loaded:', file, err?.message || err); return null; });
    loading.set(file, p);
    return p;
  }
  let preloading = false;
  async function preloadEffects() {
    if (preloading || level('sound') <= 0) return;
    preloading = true;
    const files = [...new Set(Object.values(EFFECTS).map(e => e.file))];
    // a few at a time, the interface first (they are the first heard)
    const queue = files.sort((a, b) => (/click|select|open|close|joined|lift/.test(b) ? 1 : 0) - (/click|select|open|close|joined|lift/.test(a) ? 1 : 0));
    const worker = async () => { while (queue.length) await load(queue.shift()); };
    await Promise.all([worker(), worker(), worker()]);
  }

  // --- music -------------------------------------------------------------------------------------
  const wanted = () => (level('music') > 0 ? SCENES[scene]?.track ?? null : null);
  // decoded music kept for the scene now and the one that may follow it
  const KEEP = { menu: ['lobby'], intro: ['lobby'], game: ['game', 'final'], final: ['final', 'game'], end: ['game'], none: [] };

  function startTrack(name, buf, fadeIn) {
    const def = MUSIC[name];
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.loop = !!def.loop;
    if (def.loop) { src.loopStart = def.loopStart; src.loopEnd = Math.min(def.loopEnd, buf.duration); }
    const g = ctx.createGain();
    g.gain.value = 0;
    src.connect(g); g.connect(musicBus);
    const now = ctx.currentTime;
    g.gain.setTargetAtTime(dbGain(TRACK_GAIN[name] ?? 0), now, Math.max(0.05, fadeIn / 4));
    src.start(now, def.loop ? def.loopStart : 0);
    tracks.set(name, { src, gain: g, fading: false, timer: 0 });
    note(`music:${name}`, 'start');
  }
  // Fade a track out, then stop it (a timer, not a scheduled stop: if the scene wants it back
  // meanwhile, it simply fades up again from where it is).
  function fadeOutTrack(name, s) {
    const t = tracks.get(name);
    if (!t || t.fading) return;
    t.fading = true;
    const now = ctx.currentTime;
    t.gain.gain.cancelScheduledValues(now);
    t.gain.gain.setTargetAtTime(0, now, Math.max(0.05, s / 4));
    t.timer = setTimeout(() => {
      if (!t.fading) return;
      try { t.src.stop(); } catch { /* already stopped */ }
      try { t.gain.disconnect(); } catch { /* ignore */ }
      if (tracks.get(name) === t) tracks.delete(name);
      release();
    }, (s * 1.4 + 0.1) * 1000);
    note(`music:${name}`, 'fade out');
  }
  function fadeBackIn(name, t) {
    clearTimeout(t.timer);
    t.fading = false;
    const now = ctx.currentTime;
    t.gain.gain.cancelScheduledValues(now);
    t.gain.gain.setTargetAtTime(dbGain(TRACK_GAIN[name] ?? 0), now, 0.4);
    note(`music:${name}`, 'back');
  }
  // drop decoded music that is neither playing nor near (see KEEP)
  function release() {
    const keep = new Set(KEEP[scene] || []);
    for (const name of Object.keys(MUSIC)) {
      const done = MUSIC[name].loop ? !keep.has(name) && !tracks.has(name) : scene !== 'end';
      if (done) buffers.delete(MUSIC[name].file);
    }
  }
  function syncMusic(fadeOverride) {
    if (!ctx || !unlocked) return;
    const want = wanted();
    const sc = SCENES[scene] || {};
    for (const [name, t] of tracks) {
      if (name === want) { if (t.fading) fadeBackIn(name, t); continue; }
      fadeOutTrack(name, fadeOverride ?? sc.fadeOut ?? 1.5);
    }
    current = want;
    if (!want || tracks.has(want)) { release(); return; }
    load(MUSIC[want].file).then(buf => {
      if (!buf || current !== want || tracks.has(want) || !ctx) return;
      startTrack(want, buf, fadeOverride ?? sc.fadeIn ?? 2);
      release();
    });
  }

  function setScene(name) {
    if (!SCENES[name]) return;
    if (name === scene) return;
    scene = name;
    note(`scene:${name}`, 'scene');
    // before the first tap nothing can play, but the music can already be on its way
    const track = SCENES[name]?.track;
    if (!unlocked && track && level('music') > 0) prefetchBytes(MUSIC[track].file);
    try { syncMusic(); } catch (err) { console.warn('music:', err); }
  }

  // --- stingers (music, on the end screen) ---------------------------------------------------------
  // Every stinger sounding (a dawn ending has two: the bells, then the side's own), so leaving the end
  // screen stops them all; one still loading when they are stopped never starts (stingerGen).
  const stingers = new Set();
  let stingerGen = 0;
  function stinger(name, { delay = 0, volume = 1 } = {}) {
    note(name, 'stinger');
    if (!ctx || !unlocked || level('music') <= 0 || !MUSIC[name]) return;
    const askedAt = ctx.currentTime;
    const gen = stingerGen;
    load(MUSIC[name].file).then(buf => {
      if (!buf || !ctx || gen !== stingerGen) return;
      if (ctx.currentTime - askedAt > 2.5) return;       // too late to mean anything
      const src = ctx.createBufferSource();
      src.buffer = buf;
      const g = ctx.createGain();
      g.gain.value = dbGain(STINGER_GAIN + (CUES[name]?.gain || 0)) * volume;
      src.connect(g); g.connect(musicBus);
      src.start(Math.max(ctx.currentTime, askedAt + delay));
      stingers.add(src);
      src.onended = () => { stingers.delete(src); try { g.disconnect(); } catch { /* ignore */ } };
    });
  }
  function stopStinger() {
    stingerGen++;
    for (const s of stingers) { try { s.stop(); } catch { /* ignore */ } }
    stingers.clear();
  }

  // --- effects -----------------------------------------------------------------------------------
  const rand = () => Math.random() * 2 - 1;
  function play(name, opts = {}) {
    const def = CUES[name];
    if (!def) { note(name, 'unknown cue'); return; }
    if (def.stinger) { stinger(def.stinger, opts); return; }
    if (!ctx || !unlocked) { note(name, 'locked'); return; }
    if (level('sound') <= 0) { note(name, 'sound off'); return; }
    if ((opts.volume ?? 1) <= 0.001) { note(name, 'silent'); return; }
    const now = ctx.currentTime;
    if (def.gap && now - (lastAt[name] ?? -9) < def.gap) { note(name, 'repeat dropped'); return; }
    lastAt[name] = now;
    const lib = EFFECTS[def.file];
    if (!lib) { note(name, 'no file'); return; }
    const buf = buffers.get(lib.file);
    if (buf) { voice(name, def, lib, buf, opts); return; }
    load(lib.file).then(b => { if (b && ctx && ctx.currentTime - now < 0.35) voice(name, def, lib, b, opts); });
    note(name, 'loading');
  }
  function voice(name, def, lib, buf, opts) {
    // too many at once: a minor sound gives way; otherwise the oldest minor one is cut
    const live = voices.filter(v => v.name === name);
    if (def.max && live.length >= def.max) stopVoice(live[0]);
    if (voices.length >= MAX_VOICES) {
      if (def.low) { note(name, 'too many'); return; }
      const victim = voices.find(v => v.low) || voices[0];
      stopVoice(victim);
    }
    const src = ctx.createBufferSource();
    src.buffer = buf;
    const rate = (def.vary ? Math.pow(2, (rand() * def.vary) / 12) : 1) * (opts.rate || 1);
    src.playbackRate.value = rate;
    const g = ctx.createGain();
    const vol = Math.max(0, Math.min(2, opts.volume ?? 1));
    g.gain.value = dbGain((def.gain || 0) + (def.jitter ? rand() * def.jitter : 0)) * vol;
    let tail = g;
    if (opts.pan && ctx.createStereoPanner) {
      const p = ctx.createStereoPanner();
      p.pan.value = Math.max(-1, Math.min(1, opts.pan));
      g.connect(p); tail = p;
    }
    src.connect(g); tail.connect(sfxBus);
    const when = ctx.currentTime + Math.max(0, opts.delay || 0);
    let offset = 0, dur;
    if (def.sliced && lib.slices) {
      const list = lib.slices[opts.surface] || lib.slices.carpet || Object.values(lib.slices)[0];
      let k = Math.floor(Math.random() * list.length);
      if (list.length > 1 && k === lastSlice[name]) k = (k + 1) % list.length;
      lastSlice[name] = k;
      [offset, dur] = list[k];
    }
    src.start(when, offset, dur);
    const v = { name, src, low: !!def.low, out: tail, gain: g };
    voices.push(v);
    src.onended = () => {
      const i = voices.indexOf(v);
      if (i >= 0) voices.splice(i, 1);
      try { tail.disconnect(); if (tail !== g) g.disconnect(); } catch { /* ignore */ }
    };
    note(name, 'played', { vol: +vol.toFixed(2), rate: +rate.toFixed(3), ...(opts.surface ? { surface: opts.surface } : {}) });
  }
  function stopVoice(v) {
    if (!v) return;
    try { v.gain.gain.setTargetAtTime(0, ctx.currentTime, 0.015); v.src.stop(ctx.currentTime + 0.08); } catch { /* ignore */ }
    const i = voices.indexOf(v);
    if (i >= 0) voices.splice(i, 1);
  }

  // every cue of the bus
  onSfx((name, opts) => { try { play(name, opts || {}); } catch (err) { console.warn('sound cue failed:', name, err); } });

  // --- buttons: one listener for every press (no per-button wiring) -------------------------------
  const OPENERS = /^(btn-menu-bots|btn-menu-settings|btn-private|btn-map|btn-hand)/;
  const CLOSERS = /(back|cancel|close|done)/i;
  doc.addEventListener('click', e => {
    const b = e.target?.closest?.('button, .btn, .menu-btn, .seg-btn, .ctl');
    if (!b || b.disabled || b.getAttribute('aria-disabled') === 'true') return;
    const kind = b.dataset?.sfx || (b.classList.contains('seg-btn') ? 'select'
      : CLOSERS.test(b.id || '') ? 'close' : OPENERS.test(b.id || '') ? 'open' : 'click');
    if (kind !== 'none') play(kind);
  }, true);

  // --- settings ----------------------------------------------------------------------------------
  let sleepT = 0;
  function applySettings() {
    if (!ctx) { if (!silent()) gesture(); return; }   // (both were Off until now: this tap starts it)
    const now = ctx.currentTime;
    musicBus.gain.setTargetAtTime(level('music'), now, 0.08);
    sfxBus.gain.setTargetAtTime(level('sound'), now, 0.05);
    if (level('music') <= 0) {
      for (const name of [...tracks.keys()]) fadeOutTrack(name, 0.3);
      stopStinger();
      current = null;
    } else syncMusic(1.0);
    if (level('sound') > 0) preloadEffects();
    // Both Off: asleep, and the audio session given back (after the fade-outs above have had a moment).
    // One back on: awake again (the Settings tap is a gesture, so the browser allows it).
    clearTimeout(sleepT);
    if (silent()) {
      sleepT = setTimeout(() => {
        if (!ctx || !silent()) return;
        try { ctx.suspend?.().catch?.(() => {}); } catch { /* ignore */ }
        setSession('auto');
        note('asleep', 'music and sound off');
      }, 400);
    } else {
      setSession('playback');
      if (ctx.state !== 'running' && !doc.hidden) {
        try { ctx.resume?.().then?.(() => { if (ctx.state === 'running') onRunning(); }).catch?.(() => {}); } catch { /* ignore */ }
      }
    }
  }

  function prefetch(track) {
    if (ctx && unlocked && level('music') > 0 && MUSIC[track]) load(MUSIC[track].file);
  }

  const api = {
    setScene, stinger, stopStinger, applySettings, prefetch, play,
    get scene() { return scene; },
    // tests / debugging
    state: () => ({
      ok: true, context: ctx?.state ?? 'none', unlocked, scene, track: current,
      playing: [...tracks].filter(([, t]) => !t.fading).map(([n]) => n), fading: [...tracks].filter(([, t]) => t.fading).map(([n]) => n),
      decoded: [...buffers.keys()], failed: [...failed], voices: voices.map(v => v.name), sampleRate: ctx?.sampleRate ?? 0,
      music: level('music'), sound: level('sound'),
    }),
  };
  win.__audio = api;
  return api;
}
